### PR TITLE
Remove mysql4 and apache 1.x support

### PR DESCRIPTION
**Pull request by andyli**
@ncannasse Please let me know if there is any issue for this.

### CODE REVIEW

**Comment by ncannasse** [comment]
For Apache yes I don't think there's much Apache 1.x out there.

For MySQL it's a bit more complex, because our own "mysql5" version does support only a subset of the possibilities of the mysql library. In particular you need to connect through TCP socket, you cannot connect using Unix socket, and I think some login modes are not possible (alt encryption methods etc.)

OTOH our mysql client is faster, lightweight, and consumes less memory.

**Comment by nadako** [comment]
I remember upgrading the `mysql` ndll to some new version when I was trying to get it compiled on Windows...

**Comment by nadako** [comment]
see #43

**Comment by nadako** [comment]
Looks like the mysql lib is actually recent: https://github.com/HaxeFoundation/neko/blob/master/libs/include/mysql/mysql_version.h#L21

**Comment by andyli** [comment]
I've just cherry-picked the commit that remove apache 1 (https://github.com/HaxeFoundation/neko/commit/9b919d718aa2ddb764c015752435144c5ca723ab).

For mysql, may be we should look into using the [LGPL mariadb connector](https://downloads.mariadb.org/connector-c/)?

**Comment by ncannasse** [comment]
While we're at it: we should ship mod_neko + mod_tora binaries for both apache 2.2 and 2.4 since they are incompatible in terms of modules :'(

**Comment by andyli** [comment]
I will deal with mysql soon.

**Pull request closed without merging**
