### PR TITLE
Add socket_set_keepalive

### PR DESCRIPTION
**Pull request by pperidont**
Fully tested on Linux

### CODE REVIEW

**Comment by delahee** [comment]
@ncannasse can you feedback please?

**Comment by ncannasse** [comment]
Do you think you could complete + test the Windows implementation using this ?
https://msdn.microsoft.com/en-us/library/windows/desktop/dd877220(v=vs.85).aspx

**Comment by andyli** [comment]
This PR broke neko on mac: https://travis-ci.org/HaxeFoundation/haxe/jobs/65109578#L1557

**Comment by ncannasse** [comment]
@pperidont could we quickly have a fix for OSX support ? (maybe just a missing include)

**Comment by Simn** [comment]
`<ousado> seems to be TCPCTL_KEEPIDLE on mac, if it's equivalent`

**Comment by Simn** [comment]
I have reverted the change for now.

**Pull request merged**
