### PR TITLE
Fixed stack alignment for 32-bit OS's. Closes #31

### LINKED ISSUE #31: Time for a new release?
It seems that there are many useful fixes and improvements in current master branch, some of which I believe are required by newer Haxe (e.g. `buffer_get_length` and UDP socket stuff), so why there are no new Neko release? Is it still unstable?

### PR DESCRIPTION
**Pull request by waneck**
Finally were able to test it. -mstackrealign didn't work, but this one did it!

### CODE REVIEW

**Comment by ncannasse** [comment]
Just to ping back on this issue : I think that using shell command will fail when using the makefile on windows, so we need to fix this before merging the PR. Can you look into it ?

**Comment by Simn** [comment]
(This seems to be linked to the wrong issue #31).

**Comment by ppenzin** [comment]
This will break with Clang, the flag is only supported by GCC. I will see what can be done though.

**Comment by ppenzin** [comment]
Does anyone know what the correct issue for this is? That would help a lot

**Comment by ncannasse** [comment]
The issue is because of the ABI for system calls. Before, it was valid to call any function using an alignment of 2bytes (32 bits), but some compilers requires now an alignment of 4 bytes (64 bits) even on 32 bits systems. The Neko JIT does perform 32 bits alignement, not 64 bits (which is the reason why it's disabled on OSX BTW, since the OSX ABI is 64 bits aligned from the start).

Using `-mincoming-stack-boundary=2` will tell gcc that it needs to eventually realign the stack on 64 bits prior to any system call. I wonder if there's a clang/OSX flag for this, which means we could activate the JIT

**Comment by ppenzin** [comment]
Clang has -mstack-alignment=<val> argument, not sure if that would work (I am guessing it might work if it is similar to GCC's -mpreferred-stack-alignment), need to experiment.

**Comment by ncannasse** [comment]
@ppenzin could you check it ? You only need to enable JIT in vm/jit_x86.c (remove the && !defined(NEKO_MAC)

**Comment by ppenzin** [comment]
@ncannasse I'll try. Are there any extra tests that you would recommend
running?

**Pull request merged**
