### PR TITLE
CMake

### PR DESCRIPTION
**Pull request by andyli**
This replaces the Makefile, Visual Studio projects, install.neko, and release.neko with a unified CMakeLists.txt, which can let CMake generates Makefiles and Visual Studio projects. It is already able to build Neko in Windows, Mac, and Linux. The simplest usage is documented in README.

CMake is able to help in a number of aspects. While they are not implemented yet, the following can be done quite easily with CMake:
 * to download and build 3rd-party libraries
   * It is needed for building portable binary archives for distribution because several libraries provided by homebrew/apt-get are compiled without `-fPIC`, thus cannot be statically linked to the ndlls... Currently the libraries are dynamically linked to ndlls except for Windows.
 * to have a single place (CMakeLists.txt) to declare Neko version, usable in C source
 * to embed build info into compilation output (displayed by `neko -version`)
 * to generate installers for Windows/Mac

I would like this PR to be merged now. I will update haxe/hxcpp CIs once it is merged. However,  before making a new neko release, I still need a few days to sort out the first point above (download and build 3rd-party libraries).

### CODE REVIEW

**Comment by Simn** [comment]
Nice!

I tried it and have some issues with zlib.ndll, but that might be something on my end (it says `error LNK2026: module unsafe for SAFESEH image. C:\GitHub\neko\bin\zlib.lib(inffas32.obj)`). I'll check that out tomorrow.

I'm all for removing the VS files from the repository, they are very annoying because VS always wants to upgrade them and then you have changes in the versioned files.

**Comment by nadako** [comment]
I guess CMake is good after all, gotta learn to use it!

**Comment by Simn** [comment]
I use the GUI, so for me it was:

* Set source code directory
* Set binary directory
* Click Configure
* (Select correct VS version if it asks you)
* Click Generate

**Comment by andyli** [comment]
@Simn Are you using VS2010? I had that problem with later versions of VS. It could be solved after I implement that "download and build 3rd-party libraries", which will remove the pre-compiled .lib files.

**Comment by Simn** [comment]
VS2010 wouldn't work even though I have it installed:

```
CMake Warning at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/InstallRequiredSystemLibraries.cmake:424 (message):
  system runtime library file does not exist:
  'MSVC10_REDIST_DIR-NOTFOUND/x86/Microsoft.VC100.CRT/msvcp100.dll'
```

That's again probably something on my end, I'll check it tomorrow.

**Comment by andyli** [comment]
That one is a warning which can be safely ignored for now. It is only used when packaging an archive (to include those msvc dlls).

**Comment by Simn** [comment]
Ah you're right, it was so red that I thought it had errored.

```
========== Build: 16 succeeded, 0 failed, 0 up-to-date, 9 skipped ==========
```

All good!

**Comment by ppenzin** [comment]
Great idea and good work! One comment though: your change makes all third-party dependencies (Apache, MySQL, GTK, etc), required, while before those were clearly optional (build would just skip building the corresponding .ndll if the dependency is not found).

Just curious if that was your intention.

```
$ cmake ..
-- The C compiler identification is Clang 3.4.1
-- The CXX compiler identification is Clang 3.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/CC
-- Check for working CXX compiler: /usr/bin/CC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- GC: /usr/local/include
-- GC_LIBRARIES: /usr/local/lib/libgc.so
-- GC_STATIC_LIBRARIES: GC_STATIC_LIBRARIES-NOTFOUND
-- Zlib: /usr/include
-- ZLIB_LIBRARIES: /usr/lib/libz.so
-- ZLIB_STATIC_LIBRARIES: /usr/lib/libz.a
-- Found dynamic MySQL client library: /usr/local/lib/mysql/libmysqlclient.so
-- Found statc MySQL client library: /usr/local/lib/mysql/libmysqlclient.a
-- Looking for LIBMARIADB
-- Looking for LIBMARIADB - not found
-- Found OpenSSL: /usr/lib/libssl.so;/usr/lib/libcrypto.so (found version "1.0.1p") 
-- Found PCRE 
-- Found Sqlite3: /usr/local/lib/libsqlite3.so  
-- SQLITE3_INCLUDE_DIRS /usr/local/include
-- SQLITE3_LIBRARIES /usr/local/lib/libsqlite3.so
-- SQLITE3_STATIC_LIBRARIES /usr/local/lib/libsqlite3.a
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.28") 
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.29
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find APACHE (missing: APACHE_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindAPACHE.cmake:31 (find_package_handle_standard_args)
  CMakeLists.txt:368 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by andyli** [comment]
@ppenzin It is in fact intentional. I was tricked by the auto skipping "feature" several times during packaging.
I may add options to manually skip some ndlls.

**Comment by Simn** [comment]
@ncannasse: Any objections? I'd like to see this move forward.

**Comment by ppenzin** [comment]
@andyli sounds great, that makes it easier to port actually (though I hate to have to install full Apache just to get its ndll compiled...)

**Comment by andyli** [comment]
With another bunch of commits, I'm now quite satisfied with the result.

It is now able to download and build dependencies via CMake, on all Windows, Mac, and Linux. The pre-compiled Windows libs are removed.
VS 2010 and 2013 are supported. VS 2015 is not supported since Boehm GC cannot be compiled with it for reasons that I haven't looked into yet.
A `WITH_NDLLS` CMake option is added for controlling which ndll files to be built.

I've tested the output with haxe's unit test and sys test, both passed. I've also manually tested mod_neko/tora on Windows and Mac (homebrew's), all worked fine.

**Comment by andyli** [comment]
If there is no other concern, I will merge it tomorrow.

**Comment by Simn** [comment]
I don't know what happened but trying to run CMake now complains about *perl* of all things missing:

```
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Perl (missing: PERL_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindPerl.cmake:86 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:369 (find_package)
```

**Comment by Simn** [comment]
Also I can't build it anymore. Here's my build log:

```
1>------ Skipped Build: Project: RUN_TESTS, Configuration: Release Win32 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: APR, Configuration: Release Win32 ------
3>------ Build started: Project: OpenSSL, Configuration: Release Win32 ------
4>------ Build started: Project: BoehmGC, Configuration: Release Win32 ------
5>------ Build started: Project: PCRE, Configuration: Release Win32 ------
6>------ Build started: Project: Zlib, Configuration: Release Win32 ------
7>------ Build started: Project: MbedTLS, Configuration: Release Win32 ------
8>------ Skipped Build: Project: Nightly, Configuration: Release Win32 ------
8>Project not selected to build for this solution configuration 
9>------ Skipped Build: Project: NightlyMemoryCheck, Configuration: Release Win32 ------
9>Project not selected to build for this solution configuration 
10>------ Skipped Build: Project: Experimental, Configuration: Release Win32 ------
10>Project not selected to build for this solution configuration 
11>------ Skipped Build: Project: Continuous, Configuration: Release Win32 ------
11>Project not selected to build for this solution configuration 
12>------ Skipped Build: Project: source_archive, Configuration: Release Win32 ------
12>Project not selected to build for this solution configuration 
13>------ Skipped Build: Project: uninstall, Configuration: Release Win32 ------
13>Project not selected to build for this solution configuration 
3>  Building Custom Rule C:/GitHub/neko/CMakeLists.txt
7>  Building Custom Rule C:/GitHub/neko/CMakeLists.txt
3>  CMake does not need to re-run because C:\GitHub\neko\CMakeFiles\generate.stamp is up-to-date.
7>  CMake does not need to re-run because C:\GitHub\neko\CMakeFiles\generate.stamp is up-to-date.
3>  Creating directories for 'OpenSSL'
7>  Creating directories for 'MbedTLS'
14>------ Build started: Project: gcmt-dll.dll, Configuration: Release Win32 ------
3>  Performing download step (download, verify and extract) for 'OpenSSL'
7>  Performing download step (download, verify and extract) for 'MbedTLS'
7>  -- downloading...
7>       src='https://tls.mbed.org/download/mbedtls-2.2.1-apache.tgz'
7>       dst='C:/GitHub/neko/libs/src/mbedtls-2.2.1-apache.tgz'
7>       timeout='none'
3>  -- verifying file...
3>       file='C:/GitHub/neko/libs/src/openssl-1.0.2g.tar.gz'
3>  -- verifying file... done
3>  -- extracting...
3>       src='C:/GitHub/neko/libs/src/openssl-1.0.2g.tar.gz'
3>       dst='C:/GitHub/neko/libs/src/OpenSSL'
3>  -- extracting... [tar xfz]
7>  CMake Error at MbedTLS-stamp/download-MbedTLS.cmake:27 (message):
7>CUSTOMBUILD : error : downloading 'https://tls.mbed.org/download/mbedtls-2.2.1-apache.tgz'
7>    failed
7>  
7>      status_code: 51
7>      status_string: "SSL peer certificate was not ok"
7>      log: About to connect() to tls.mbed.org port 443 (#0)
7>      Trying 79.170.91.36... connected
7>  
7>    Connected to tls.mbed.org (79.170.91.36) port 443 (#0)
7>  
7>    libcurl is now using a weak random seed!
7>  
7>    SSLv3, TLS handshake, Client hello (1):
7>  
7>    
7>  
7>  
7>  
15>------ Build started: Project: compilers, Configuration: Release Win32 ------
16>------ Build started: Project: ssl.ndll, Configuration: Release Win32 ------
16>  ssl.c
16>libs\ssl\ssl.c(25): fatal error C1083: Cannot open include file: 'mbedtls/error.h': No such file or directory
3>  -- extracting... [analysis]
3>  -- extracting... [rename]
3>  -- extracting... [clean up]
3>  -- extracting... done
3>  No update step for 'OpenSSL'
3>  No patch step for 'OpenSSL'
3>  Performing configure step for 'OpenSSL'
3>CUSTOMBUILD : error : Could not process argument VC-WIN32
3>  invalid character: -
17>------ Build started: Project: APRutil, Configuration: Release Win32 ------
18>------ Build started: Project: MariaDBConnector, Configuration: Release Win32 ------
17>  Building Custom Rule C:/GitHub/neko/CMakeLists.txt
17>  CMake does not need to re-run because C:\GitHub\neko\CMakeFiles\generate.stamp is up-to-date.
17>  Creating directories for 'APRutil'
18>  Building Custom Rule C:/GitHub/neko/CMakeLists.txt
18>  CMake does not need to re-run because C:\GitHub\neko\CMakeFiles\generate.stamp is up-to-date.
18>  Creating directories for 'MariaDBConnector'
17>  Performing download step (download, verify and extract) for 'APRutil'
18>  Performing download step (download, verify and extract) for 'MariaDBConnector'
17>  -- verifying file...
17>       file='C:/GitHub/neko/libs/src/apr-util-1.5.4.tar.gz'
17>  -- verifying file... done
17>  -- extracting...
17>       src='C:/GitHub/neko/libs/src/apr-util-1.5.4.tar.gz'
17>       dst='C:/GitHub/neko/libs/src/APRutil'
17>  -- extracting... [tar xfz]
18>  -- verifying file...
18>       file='C:/GitHub/neko/libs/src/mariadb-connector-c-2.2.2-src.tar.gz'
18>  -- verifying file... done
18>  -- extracting...
18>       src='C:/GitHub/neko/libs/src/mariadb-connector-c-2.2.2-src.tar.gz'
18>       dst='C:/GitHub/neko/libs/src/MariaDBConnector'
18>  -- extracting... [tar xfz]
18>  -- extracting... [analysis]
18>  -- extracting... [rename]
18>  -- extracting... [clean up]
18>  -- extracting... done
18>  No update step for 'MariaDBConnector'
18>  Performing patch step for 'MariaDBConnector'
18>  Performing configure step for 'MariaDBConnector'
18>  -- CMAKE_C_FLAGS_DEBUG= /D_DEBUG /MDd /Zi /Ob0 /Od /RTC1
18>  -- CMAKE_C_FLAGS_RELEASE= /MD /O2 /Ob2 /D NDEBUG
18>  -- CMAKE_C_FLAGS_RELWITHDEBINFO= /MD /Zi /O2 /Ob1 /D NDEBUG
18>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:293 (list):
18>    list GET given empty list
18>  Call Stack (most recent call first):
18>    CMakeLists.txt:169 (FIND_PACKAGE)
18>  
18>  
18>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:294 (list):
18>    list GET given empty list
18>  Call Stack (most recent call first):
18>    CMakeLists.txt:169 (FIND_PACKAGE)
18>  
18>  
18>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:296 (list):
18>    list GET given empty list
18>  Call Stack (most recent call first):
18>    CMakeLists.txt:169 (FIND_PACKAGE)
18>  
18>  
18>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:298 (list):
18>    list GET given empty list
18>  Call Stack (most recent call first):
18>    CMakeLists.txt:169 (FIND_PACKAGE)
18>  
18>  
17>  -- extracting... [analysis]
17>  -- extracting... [rename]
18>  -- MariaDB Connector/c configuration:
18>  -- CPack generation: ZIP
18>  -- SSL support: ON
18>  -- Experimental Sqlite support: 
18>  -- Zlib support: yes (using bundled zlib)
18>  -- Installation layout: DEFAULT
18>  -- Include files will be installed in /include/mariadb
18>  -- Libraries will be installed in /lib/mariadb
18>  -- Binaries will be installed in /bin
18>  -- Required: 
18>  -- Configuring incomplete, errors occurred!
18>  See also "C:/GitHub/neko/libs/src/MariaDBConnector-build/CMakeFiles/CMakeOutput.log".
18>  See also "C:/GitHub/neko/libs/src/MariaDBConnector-build/CMakeFiles/CMakeError.log".
17>  -- extracting... [clean up]
17>  -- extracting... done
18>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 1.
17>  No update step for 'APRutil'
17>  No patch step for 'APRutil'
17>  Performing configure step for 'APRutil'
17>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:293 (list):
17>    list GET given empty list
17>  Call Stack (most recent call first):
17>    CMakeLists.txt:22 (FIND_PACKAGE)
17>  
17>  
17>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:294 (list):
17>    list GET given empty list
17>  Call Stack (most recent call first):
17>    CMakeLists.txt:22 (FIND_PACKAGE)
17>  
17>  
17>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:296 (list):
17>    list GET given empty list
17>  Call Stack (most recent call first):
17>    CMakeLists.txt:22 (FIND_PACKAGE)
17>  
17>  
17>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:298 (list):
17>    list GET given empty list
17>  Call Stack (most recent call first):
17>    CMakeLists.txt:22 (FIND_PACKAGE)
17>  
17>  
17>  -- 
17>  -- 
17>  -- APR-Util configuration summary:
17>  -- 
17>  --   Build type ...................... : 
17>  --   Install .pdb (if available)...... : OFF
17>  --   Install prefix .................. : C:/GitHub/neko/libs/src/install-prefix
17>  --   C compiler ...................... : c:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe
17>  --   APR include directory ........... : C:/GitHub/neko/libs/src/install-prefix/include
17>  --   APR libraries ................... : C:/GitHub/neko/libs/src/install-prefix/lib/libapr-1.lib
17>  --   DBD ODBC driver ................. : ON
17>  --   APU_HAVE_CRYPTO ................. : OFF
17>  --   APR_HAS_LDAP .................... : ON
17>  --   Build test suite ................ : OFF
17>  --     (testing dynamic libraries)
17>  -- Configuring incomplete, errors occurred!
17>  See also "C:/GitHub/neko/libs/src/APRutil-build/CMakeFiles/CMakeOutput.log".
17>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 1.
19>------ Build started: Project: mysql.ndll, Configuration: Release Win32 ------
19>  mysql.c
19>LINK : fatal error LNK1181: cannot open input file 'libs\src\install-prefix\lib\libeay32.lib'
20>------ Build started: Project: Apache, Configuration: Release Win32 ------
20>  Building Custom Rule C:/GitHub/neko/CMakeLists.txt
20>  CMake does not need to re-run because C:\GitHub\neko\CMakeFiles\generate.stamp is up-to-date.
20>  Creating directories for 'Apache'
20>  Performing download step (download, verify and extract) for 'Apache'
20>  -- verifying file...
20>       file='C:/GitHub/neko/libs/src/httpd-2.4.20.tar.gz'
20>  -- verifying file... done
20>  -- extracting...
20>       src='C:/GitHub/neko/libs/src/httpd-2.4.20.tar.gz'
20>       dst='C:/GitHub/neko/libs/src/Apache'
20>  -- extracting... [tar xfz]
20>  -- extracting... [analysis]
20>  -- extracting... [rename]
20>  -- extracting... [clean up]
20>  -- extracting... done
20>  No update step for 'Apache'
20>  No patch step for 'Apache'
20>  Performing configure step for 'Apache'
20>  -- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR) 
20>  -- Could NOT find Lua51 (missing:  LUA_LIBRARIES) 
20>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:293 (list):
20>    list GET given empty list
20>  Call Stack (most recent call first):
20>    CMakeLists.txt:27 (FIND_PACKAGE)
20>  
20>  
20>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:294 (list):
20>    list GET given empty list
20>  Call Stack (most recent call first):
20>    CMakeLists.txt:27 (FIND_PACKAGE)
20>  
20>  
20>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:296 (list):
20>    list GET given empty list
20>  Call Stack (most recent call first):
20>    CMakeLists.txt:27 (FIND_PACKAGE)
20>  
20>  
20>  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.1/Modules/FindOpenSSL.cmake:298 (list):
20>    list GET given empty list
20>  Call Stack (most recent call first):
20>    CMakeLists.txt:27 (FIND_PACKAGE)
20>  
20>  
20>  CMake Error at CMakeLists.txt:86 (MESSAGE):
20>    APR library C:/GitHub/neko/libs/src/install-prefix/lib/libaprutil-1.lib was
20>    not found.
20>  
20>  
20>  -- Configuring incomplete, errors occurred!
20>  See also "C:/GitHub/neko/libs/src/Apache-build/CMakeFiles/CMakeOutput.log".
20>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 1.
21>------ Build started: Project: mod_neko2.ndll, Configuration: Release Win32 ------
21>  mod_neko.c
21>c:\github\neko\libs\src\apache\include\ap_hooks.h(40): fatal error C1083: Cannot open include file: 'apr_hooks.h': No such file or directory
21>  cgi.c
21>c:\github\neko\libs\src\apache\include\ap_hooks.h(40): fatal error C1083: Cannot open include file: 'apr_hooks.h': No such file or directory
21>  Generating Code...
22>------ Build started: Project: mod_tora2.ndll, Configuration: Release Win32 ------
22>  mod_tora.c
22>c:\github\neko\libs\src\apache\include\ap_hooks.h(40): fatal error C1083: Cannot open include file: 'apr_hooks.h': No such file or directory
23>------ Skipped Build: Project: INSTALL, Configuration: Release Win32 ------
23>Project not selected to build for this solution configuration 
24>------ Skipped Build: Project: PACKAGE, Configuration: Release Win32 ------
24>Project not selected to build for this solution configuration 
========== Build: 6 succeeded, 9 failed, 10 up-to-date, 9 skipped ==========
```

Sorry for not testing this before the merge, I hadn't realized that so much changed since I last tested.

**Comment by andyli** [comment]
@Simn Perl is needed just because OpenSSL needs it for its configuration script. Install [ActivePerl](http://www.activestate.com/activeperl) to fix it.

**Comment by ncannasse** [comment]
@andyli I don't think we're using OpenSSL at all

**Comment by andyli** [comment]
@ncannasse 
MariaDB connector C and Apache depend on OpenSSL.

MariaDB connector C 3.0.0, which is currently in alpha, will remove such dependency.
I *think* Apache could be built without OpenSSL and the mod_neko/tora produced from it should be fine. Will test it once MariaDB connector C releases 3.0.0.

**Comment by ncannasse** [comment]
Why do we need to rebuild Apache in windows ?

**Comment by andyli** [comment]
To build mod_neko/tora, which need to link with libhttpd.

**Comment by ncannasse** [comment]
Yes, but did we not provide precompiled versions of it for windows?

**Comment by andyli** [comment]
They are removed as I mentioned previously in https://github.com/HaxeFoundation/neko/pull/122#issuecomment-211845115.

The problems of bundling pre-compiled lib:
 * It's hard to remember/document how to compile them.
 * They cause problems when using different versions of compilers. It happened when I tried to use VS 2013 to build Neko.
 * People cannot know what's compiled in them so generally it's bad security-wise for the users.

**Comment by Simn** [comment]
Could we add a configuration option that allows neko building for "normal" people, i.e. those that just want to use it as a Haxe target and don't need the fancy mod_neko/tora/whatever stuff?

**Comment by andyli** [comment]
It can already been done in two ways, and they should have the same effect:
 1. Specify `-DWITH_NDLLS=std.ndll;zlib.ndll` during cmake config, or
 2. Just build the `nekovm` target.

**Comment by ppenzin** [comment]
I know I am really late to the party, but I only got to work on it now. My FreeBSD build does not work yet, but there are a few things I can point out right now.

In most of the cases, missing required packages are not detected on FreeBSD, not sure why, will send a PR when figure that out.

But more importantly, variable names don't match between FindX,cmake scripts and root CMakeLists.txt, like GC_INLUDE_DIRS vs GC_INCLUDE_DIR.

**Comment by ncannasse** [comment]
I'm a bit annoyed that we now have to install Perl to compile Neko...
Could we not simply disable the MariaDB connector by default ? we already have a mysql5.ndll that does allow to connect to any mysql database over TCP.

**Pull request merged**
