### PR TITLE
Fix strip issue with 'nekotools boot' created executables on Linux ELF...

### PR DESCRIPTION
**Pull request by kulick**
We may want to discuss what, if any, other precautions we'd like to take to better support other ABIs and other platforms.  Bryan and I did look at Mac OS X and it seems that attempts to strip 'nekoc' there result in the strip tool just giving up (without damaging the executable) since it doesn't understand the extra bytes at the end of the file...

### CODE REVIEW

**Comment by kulick** [comment]
Oops.  Right, Windows.  Looks like I didn't add the new files to the Windows project file.  Not sure how well I can fix that without really being able to test it, but I'll have a look tmw.  In the meantime, feel free to look at the code here.  ;)

**Comment by kulick** [comment]
Ok, this is getting ugly.  I'm using checkins to run builds.  Ick.

I think I've placed the elf_update.c code in the wrong place (libneko when it should be in std.ndll).  Somehow that worked fine on Linux, but not on Windows.  I'm trying to sort it out now.

**Comment by kulick** [comment]
Yeah.  Well that was more fun than expected.  ;)

**Comment by ncannasse** [comment]
@kulick thanks for the contribution ! could you confirm it works with both 32 and 64 bits ELF ?

**Comment by kulick** [comment]
Designed for both.  I tested 64-bit.  I'll see if I can validate 32-bit real quick...brb.

**Comment by kulick** [comment]
Ok, just tested on a 32-bit VM image and all looks good to me.  Any specific concern or just checking?

**Comment by ncannasse** [comment]
Just checking. Merging now :)

**Comment by andyli** [comment]
@kulick 
Building neko on mac [fails with error](https://travis-ci.org/HaxeFoundation/haxe/jobs/76038572#L2208-L2213):
```
vm/neko_elf.h:36:10: fatal error: 'elf.h' file not found
#include <elf.h>
         ^
1 error generated.
make: *** [vm/elf.o] Error 1
```
Any idea?

**Comment by kulick** [comment]
Andy,

Sorry about this.  I can't really test Mac OS X or Windows build workflows.

The problem here is that we shouldn't be building on Mac with -DABI_ELF.  Hopefully the fix is simply a matter of just refactoring the addition of that compiler argument so that it only occurs on Linux.

Maybe something like this...

https://github.com/kulick/neko/commit/6334ef5504880e20b374662f935a5f4a34e9bff9

...?

Alternatively, we could require 'make os=linux' on Linux or detect Linux with something like "uname | grep '^Linux'".  Lots of solutions.

If you like my 'filter-out' solution, feel free to pull the change from my neko repo.  Or let me know if you'd like a pull request.

Thanks and, again, sorry for the hassles...

**Comment by andyli** [comment]
Thanks for the info! I have no idea about the ELF stuffs at all. I've just refactored the makefile as you've suggested (#87).

**Pull request merged**
