### PR TITLE
Generate endianness macro via CMake

### PR DESCRIPTION
**Pull request by ppenzin**
Use TEST_BIG_ENDIAN standard module/function to get a macro that can be consumed in both Neko and its libraries.

Should help with #155

### CODE REVIEW

**Comment by andyli** [comment]
Thanks!
I'm not sure if we need to preserve the defines (e.g. `LITTLE_ENDIAN`, `BIG_ENDIAN`, `BYTE_ORDER`).
Assigning to Nicolas for review.

**Comment by ncannasse** [comment]
if they are not used inside neko code, we don't need them

**Comment by ncannasse** [comment]
maybe IS_BIG_ENDIAN is

**Comment by ppenzin** [comment]
I changed that to one of the generated macros. vm/builtins.c uses NEKO_BIG_ENDIAN macro, but nothing sets is, so I left that one alone.

**Comment by ppenzin** [comment]
Ping. None of those macros are used externally, right?

**Comment by ncannasse** [comment]
If it works for you feel free to merge @andyli

**Pull request merged**
