### PR TITLE
Fix some CMake variable name mismatches

### PR DESCRIPTION
**Pull request by ppenzin**
This is related to #122, variables set by find modules are named slightly different from the variables in CMakeLists.txt.

Also trying to make the build more FreeBSD friendly.

### CODE REVIEW

**Comment by ppenzin** [comment]
Sorry for all the "Merge commit X" cruft, forgot to amend those.

**Comment by ppenzin** [comment]
I will submit a better version in a few hours.

**Comment by andyli** [comment]
I've just added you as a collaborator, so you can integrate the changes you need for packaging directly. Thanks in advance for the commits!

We can make a 2.1.1 release when you sort out everything for FreeBSD.

**Comment by ppenzin** [comment]
Awesome, thank you very much! I will commit the changes once I get them working on other platforms.

**Pull request closed without merging**
