### PR TITLE
ndlls compiled for Apache 2.2 / 2.4

### PR DESCRIPTION
**Pull request by andyli**
The "apache" branch contains changes that replaces mod_neko2/mod_tora2 with mod_neko22/mod_tora22 and mod_neko24/mod_tora24.

I've briefly checked that the ndlls work on Windows ([XAMPP](https://www.apachefriends.org/)), Mac (`brew install homebrew/apache/httpd24`), and Ubuntu (`apt-get install apache2-mpm-prefork`). But for unknown reason it does not work with the osx pre-installed apache 2.4. It would be great if you can check with your machine.

### CODE REVIEW

**Comment by ncannasse** [comment]
I don't have an OSX machine to test with, do you want me to merge as-it or wait until you found leads to the issue ?

**Comment by andyli** [comment]
Let's wait for a while and I will revisit it soon. I'm a bit worried.

**Comment by andyli** [comment]
I have spent another 3 days figuring it out why the OSX apache doesn't work but still don't have any idea. I'm asking for help from the apache module development mailing list and will continue to investigate if there is any new idea. 

For now I hope to get it merged and conclude that there is some weird issue with the OSX apache and  users should either
 1. use the homebrew apache, or
 2. use mod_tora, which does work on the OSX apache

**Comment by Simn** [comment]
Maybe @Jens-G has an idea.

**Comment by Jens-G** [comment]
Hi, no sorry, he hasn't. 

Maybe I have to explain a bit. The days where Apache hosted only /the/ [Apache httpd](https://httpd.apache.org/) are over. As of today, the ASF hosts [over 200 open source projects](http://projects-old.apache.org/indexes/alpha.html). If you want to ask something about the [Apache Thrift](http://thrift.apache.org) cross-language, cross-platform serialization and RPC framework, you are welcome. But my expertise with httpd is ... well, limited. Very limited, actually.

Sorry I couldn't help you out.

**Comment by Simn** [comment]
Oh sorry, I guess I was thinking of someone else then!

**Comment by andyli** [comment]
@ncannasse Do you want this to be merged? If so, I will deal with the merge conflict and push to master.

FYI, it is fine if we decide to abandon this PR and just compile the ndll against Apache 2.4. It seems most people use 2.4 this days. And if I remember correctly, even without this PR, the mod_neko ndll compiled against Apache 2.4 still suffers from the same problem with OSX bundled Apache.

**Comment by ncannasse** [comment]
Could you do the necessary so that mod_neko2.ndll (and mod_tora2) both use Apache 2.4 ?

**Comment by andyli** [comment]
It is already the case if Apache 2.4 is installed during compilation.
The recent Debian/Ubuntu and homebrew packages also bundle the ndlls compiled with Apache 2.4 because the system Apache is 2.4.

So I will just close this then :)

**Comment by andyli** [comment]
Ahh. I forgot that the bundled Apache source and lib in the repo used by Windows need updating.
Will do so now.

**Comment by andyli** [comment]
done

**Pull request closed without merging**
