### PR TITLE
Update copyright year in files

### PR DESCRIPTION
**Pull request by tobil4sk**

### CODE REVIEW

**Comment by Simn** [comment]
I think we stopped doing this at some point because it's just annoying. I'll go ahead and close.

**Comment by tobil4sk** [comment]
@Simn My main reason for this was to update the date on the neko usage message if there's going to have to be a release for #247 and the other fixes. I guess that message could be auto generated by the build system to fix that at least?

**Comment by Simn** [comment]
Mmh I guess we can change that, yeah...

**Comment by Simn** [comment]
Could you check the conflict?

**Pull request merged**
